# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 975db4c5dbf2c955f9f3040c31efad49704467fb383f0444e22d39a3ae0d199c4c6c868cf7b4ad45fc10e6a702bc070fdf09bfa8140edd522cf0b23420bb5857

test:
  secret_key_base: 037acdb1bec2b460034a163366c99d272d52e4becdd2219b08736348e55eec55be2bf04474eae72b393f65b9253f4026a58815f8389599ca45a5eed548374f4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
